use crate::cli::ClientConfigArgs;
use anyhow::Result;
use colored::Colorize;
use std::fs;

pub async fn run(args: ClientConfigArgs) -> Result<()> {
    let yaml = if args.ios_minimal {
        build_clash_yaml_ios_minimal(
            &args.uuid, args.cdn_host.as_deref(),
        )
    } else if args.ios {
        build_clash_yaml_ios(
            &args.host, args.vless_port, args.hy2_port,
            &args.sni, &args.uuid,
            &args.hy2_password, &args.reality_public_key, &args.reality_short_id,
            args.cdn_host.as_deref(),
        )
    } else {
        build_clash_yaml(
            &args.host, args.vless_port, args.hy2_port,
            &args.sni, &args.uuid,
            &args.hy2_password, &args.reality_public_key, &args.reality_short_id,
            args.cdn_host.as_deref(),
        )
    };

    match args.output {
        Some(ref path) => {
            fs::write(path, &yaml)?;
            println!("{}", format!("✓ Clash config written to {path}").green());
        }
        None => print!("{yaml}"),
    }

    Ok(())
}

pub fn build_clash_yaml(
    host: &str, vless_port: u16, hy2_port: u16,
    sni: &str, uuid: &str,
    hy2_pass: &str, pub_key: &str, short_id: &str,
    cdn_host: Option<&str>,
) -> String {
    let cdn_proxy = match cdn_host {
        Some(h) => format!(
            "\n  - name: \"CDN-VMess\"\n    \
             type: vmess\n    \
             server: {h}\n    \
             port: 443\n    \
             uuid: {uuid}\n    \
             alterId: 0\n    \
             cipher: auto\n    \
             network: ws\n    \
             tls: true\n    \
             servername: {h}\n    \
             skip-cert-verify: false\n    \
             ws-opts:\n      \
               path: /vmws\n      \
               headers:\n        \
                 Host: {h}\n"
        ),
        None => String::new(),
    };
    let cdn_in_fallback = if cdn_host.is_some() {
        "      - CDN-VMess\n"
    } else {
        ""
    };
    let cdn_in_select = if cdn_host.is_some() {
        "      - CDN-VMess\n"
    } else {
        ""
    };
    format!(
        r#"# Generated by godo-vps — edit rule-providers URLs if jsdelivr is blocked
mixed-port: 7890
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090
external-ui: ui

dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - "*.local"
    - localhost.ptlogin2.qq.com
    - "+.xn--7xa.monster"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
  listen: 0.0.0.0:53
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - https://1.1.1.1/dns-query
    - https://dns.google/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4

# Recover hostname from TLS SNI / QUIC ClientHello so fake-ip + HTTP/3 apps
# (Claude, ChatGPT, modern browsers) hit domain rules correctly.
sniffer:
  enable: true
  parse-pure-ip: true
  override-destination: true
  force-dns-mapping: true
  sniff:
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
    HTTP:
      ports: [80, "8080-8880"]
  skip-domain:
    - "+.xn--7xa.monster"
    - "Mijia Cloud"
    - "+.push.apple.com"

proxies:
  - name: "SG-Reality"
    type: vless
    server: {host}
    port: {vless_port}
    uuid: {uuid}
    flow: xtls-rprx-vision
    network: tcp
    tls: true
    servername: {sni}
    reality-opts:
      public-key: {pub_key}
      short-id: {short_id}
    client-fingerprint: chrome

  - name: "SG-Hysteria2"
    type: hysteria2
    server: {host}
    port: {hy2_port}
    password: {hy2_pass}
    sni: www.bing.com
    skip-cert-verify: true
    up: "30 Mbps"
    down: "200 Mbps"
{cdn_proxy}
proxy-groups:
  - name: "Proxy"
    type: fallback
    proxies:
{cdn_in_fallback}      - SG-Hysteria2
      - SG-Reality
    url: "https://www.gstatic.com/generate_204"
    interval: 60
    lazy: true

  - name: "Select"
    type: select
    proxies:
      - Proxy
{cdn_in_select}      - SG-Reality
      - SG-Hysteria2
      - DIRECT

  - name: "OpenAI"
    type: fallback
    proxies:
{cdn_in_fallback}      - SG-Hysteria2
      - SG-Reality
    url: "https://www.gstatic.com/generate_204"
    interval: 60
    lazy: true

  - name: "Streaming"
    type: fallback
    proxies:
{cdn_in_fallback}      - SG-Hysteria2
      - SG-Reality
    url: "https://www.gstatic.com/generate_204"
    interval: 60
    lazy: true

  - name: "Final"
    type: select
    proxies:
      - Proxy
      - DIRECT

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400
  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400
  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400
  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400
  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400
  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

rules:
  - RULE-SET,reject,REJECT

  # === HKUST campus → 直连（最高优先级，不让校内流量绕到新加坡） ===
  - IP-CIDR,143.89.0.0/16,DIRECT,no-resolve
  - IP-CIDR,175.159.0.0/16,DIRECT,no-resolve

  # === 香港本地 → 直连 ===
  - GEOIP,HK,DIRECT,no-resolve
  - DOMAIN-SUFFIX,hk,DIRECT
  - DOMAIN-SUFFIX,com.hk,DIRECT
  - DOMAIN-SUFFIX,edu.hk,DIRECT
  - DOMAIN-SUFFIX,gov.hk,DIRECT
  - DOMAIN-SUFFIX,org.hk,DIRECT
  - DOMAIN-SUFFIX,net.hk,DIRECT

  # === Steam / Valve 游戏（Deadlock/CS2/Dota2 等）→ 直连，避免代理拖延迟 ===
  # NOTE: DST-PORT range syntax (e.g. 27015-27050) is rejected by the OG Clash
  # core that Clash for Windows ships with. Stick to domain rules; Steam clients
  # resolve hostnames first so this catches the vast majority of game traffic.
  - DOMAIN-SUFFIX,steamserver.net,DIRECT
  - DOMAIN-SUFFIX,steamcontent.com,DIRECT
  - DOMAIN-SUFFIX,steamstatic.com,DIRECT
  - DOMAIN-KEYWORD,steampipe,DIRECT
  - DOMAIN-KEYWORD,steamcdn,DIRECT

  # === 国内社交/视频/IM 强制直连（即使被误判也不走代理） ===
  - DOMAIN-SUFFIX,xiaohongshu.com,DIRECT
  - DOMAIN-SUFFIX,xhscdn.com,DIRECT
  - DOMAIN-SUFFIX,rednotecdn.com,DIRECT
  - DOMAIN-SUFFIX,rnote.com,DIRECT
  - DOMAIN-SUFFIX,xhsstatic.com,DIRECT
  - DOMAIN-SUFFIX,bilibili.com,DIRECT
  - DOMAIN-SUFFIX,bilivideo.com,DIRECT
  - DOMAIN-SUFFIX,b23.tv,DIRECT
  - DOMAIN-KEYWORD,upos-,DIRECT
  - DOMAIN-SUFFIX,hdslb.com,DIRECT
  - DOMAIN-SUFFIX,weibo.com,DIRECT
  - DOMAIN-SUFFIX,weibo.cn,DIRECT
  - DOMAIN-SUFFIX,sinaimg.cn,DIRECT
  - DOMAIN-SUFFIX,sina.com.cn,DIRECT
  - DOMAIN-SUFFIX,wx.qq.com,DIRECT
  - DOMAIN-SUFFIX,weixin.qq.com,DIRECT
  - DOMAIN-SUFFIX,wechat.com,DIRECT
  - DOMAIN-SUFFIX,qq.com,DIRECT
  - DOMAIN-SUFFIX,tencent.com,DIRECT
  - DOMAIN-SUFFIX,tencent-cloud.net,DIRECT    # 微信视频号 P2P CDN
  - DOMAIN-SUFFIX,qpic.cn,DIRECT
  - DOMAIN-SUFFIX,gtimg.com,DIRECT
  - DOMAIN-SUFFIX,gtimg.cn,DIRECT
  - DOMAIN-SUFFIX,douyin.com,DIRECT
  - DOMAIN-SUFFIX,douyinpic.com,DIRECT
  - DOMAIN-SUFFIX,douyinvod.com,DIRECT
  - DOMAIN-SUFFIX,toutiao.com,DIRECT
  - DOMAIN-SUFFIX,zhihu.com,DIRECT
  - DOMAIN-SUFFIX,zhimg.com,DIRECT
  - DOMAIN-SUFFIX,ixigua.com,DIRECT
  - DOMAIN-SUFFIX,iqiyi.com,DIRECT
  - DOMAIN-SUFFIX,iqiyipic.com,DIRECT
  - DOMAIN-SUFFIX,youku.com,DIRECT
  - DOMAIN-SUFFIX,ykimg.com,DIRECT
  - DOMAIN-SUFFIX,mgtv.com,DIRECT
  - DOMAIN-SUFFIX,hitv.com,DIRECT
  - DOMAIN-SUFFIX,alipay.com,DIRECT
  - DOMAIN-SUFFIX,alipayobjects.com,DIRECT
  - DOMAIN-SUFFIX,taobao.com,DIRECT
  - DOMAIN-SUFFIX,tmall.com,DIRECT
  - DOMAIN-SUFFIX,jd.com,DIRECT
  - DOMAIN-SUFFIX,360buyimg.com,DIRECT
  - DOMAIN-SUFFIX,meituan.com,DIRECT
  - DOMAIN-SUFFIX,meituan.net,DIRECT

  # === 原有规则 ===
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,Proxy
  # OpenAI / ChatGPT / Atlas (Atlas browser uses chatgpt.com + Bing for search)
  - DOMAIN-SUFFIX,openai.com,OpenAI
  - DOMAIN-SUFFIX,chatgpt.com,OpenAI
  - DOMAIN-SUFFIX,oaistatic.com,OpenAI
  - DOMAIN-SUFFIX,oaiusercontent.com,OpenAI
  - DOMAIN-KEYWORD,openai,OpenAI
  - DOMAIN-SUFFIX,bing.com,OpenAI
  - DOMAIN-SUFFIX,bing.net,OpenAI
  - DOMAIN-SUFFIX,b-msn.com,OpenAI
  # Anthropic / Claude
  - DOMAIN-SUFFIX,anthropic.com,OpenAI
  - DOMAIN-SUFFIX,claude.ai,OpenAI
  - DOMAIN-KEYWORD,claude,OpenAI
  - DOMAIN-SUFFIX,netflix.com,Streaming
  - DOMAIN-SUFFIX,nflxvideo.net,Streaming
  - DOMAIN-SUFFIX,spotify.com,Streaming
  - RULE-SET,telegramcidr,Proxy,no-resolve
  - RULE-SET,proxy,Proxy
  - RULE-SET,gfw,Proxy
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT,no-resolve
  - RULE-SET,cncidr,DIRECT,no-resolve
  - GEOIP,LAN,DIRECT,no-resolve
  - GEOIP,CN,DIRECT,no-resolve
  - MATCH,Final
"#,
        host = host,
        vless_port = vless_port,
        hy2_port = hy2_port,
        sni = sni,
        uuid = uuid,
        hy2_pass = hy2_pass,
        pub_key = pub_key,
        short_id = short_id,
    )
}

/// iOS-friendly Clash/Mihomo config:
///  - no dns.listen (iOS VPN extension sandbox forbids socket binds)
///  - redir-host instead of fake-ip (more reliable inside the extension)
///  - no external-controller / external-ui / allow-lan / bind-address (sandbox)
///  - rule-providers trimmed to 3 essentials (gfw + cncidr + proxy) to stay
///    under iOS's 50 MB VPN-extension memory cap.
pub fn build_clash_yaml_ios(
    host: &str, vless_port: u16, hy2_port: u16,
    sni: &str, uuid: &str,
    hy2_pass: &str, pub_key: &str, short_id: &str,
    cdn_host: Option<&str>,
) -> String {
    let cdn_proxy = match cdn_host {
        Some(h) => format!(
            "\n  - name: \"CDN-VMess\"\n    \
             type: vmess\n    \
             server: {h}\n    \
             port: 443\n    \
             uuid: {uuid}\n    \
             alterId: 0\n    \
             cipher: auto\n    \
             network: ws\n    \
             tls: true\n    \
             servername: {h}\n    \
             skip-cert-verify: false\n    \
             ws-opts:\n      \
               path: /vmws\n      \
               headers:\n        \
                 Host: {h}\n"
        ),
        None => String::new(),
    };
    let cdn_in_fallback = if cdn_host.is_some() { "      - CDN-VMess\n" } else { "" };
    let cdn_in_select   = if cdn_host.is_some() { "      - CDN-VMess\n" } else { "" };

    format!(
        r#"# Generated by godo-vps (iOS variant) — trimmed for ClashMi / mihomo on iOS
# iOS VPN extension has a hard 50 MB memory limit; do not add more rule-providers.
# fake-ip + sniffer is REQUIRED for native iOS apps that use HTTP/3 (QUIC over UDP).
# redir-host mode leaks QUIC traffic past hostname-based rules → Claude/ChatGPT app fail.
mixed-port: 7890
mode: rule
log-level: silent
ipv6: true

dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - "*.local"
    - "localhost.ptlogin2.qq.com"
    - "+.xn--7xa.monster"   # our own proxy domain — must resolve to real IP
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - https://1.1.1.1/dns-query
    - https://dns.google/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN

# sniffer recovers the original hostname from TLS SNI / QUIC ClientHello / HTTP Host,
# so when an app fires HTTP/3 (UDP) at a fake-ip, mihomo still applies the right rule.
# parse-pure-ip + override-destination are required for fake-ip to work end-to-end on iOS.
sniffer:
  enable: true
  parse-pure-ip: true
  override-destination: true
  force-dns-mapping: true
  sniff:
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
    HTTP:
      ports: [80, "8080-8880"]
  skip-domain:
    - "+.xn--7xa.monster"
    - "Mijia Cloud"
    - "+.push.apple.com"

proxies:
  - name: "SG-Reality"
    type: vless
    server: {host}
    port: {vless_port}
    uuid: {uuid}
    flow: xtls-rprx-vision
    network: tcp
    tls: true
    servername: {sni}
    reality-opts:
      public-key: {pub_key}
      short-id: {short_id}
    client-fingerprint: chrome

  - name: "SG-Hysteria2"
    type: hysteria2
    server: {host}
    port: {hy2_port}
    password: {hy2_pass}
    sni: www.bing.com
    skip-cert-verify: true
    up: "30 Mbps"
    down: "200 Mbps"
{cdn_proxy}
proxy-groups:
  - name: "Proxy"
    type: fallback
    proxies:
{cdn_in_fallback}      - SG-Hysteria2
      - SG-Reality
    url: "https://www.gstatic.com/generate_204"
    interval: 60
    lazy: true

  - name: "Select"
    type: select
    proxies:
      - Proxy
{cdn_in_select}      - SG-Reality
      - SG-Hysteria2
      - DIRECT

rules:
  # Self-proxy domain MUST go DIRECT or we get an infinite loop.
  - DOMAIN-SUFFIX,xn--7xa.monster,DIRECT

  # LAN / loopback — always DIRECT.
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - DOMAIN-SUFFIX,local,DIRECT
  - DOMAIN-SUFFIX,lan,DIRECT

  # Bilibili — forced DIRECT (user requested).
  - DOMAIN-SUFFIX,bilibili.com,DIRECT
  - DOMAIN-SUFFIX,bilivideo.com,DIRECT
  - DOMAIN-SUFFIX,bilivideo.cn,DIRECT
  - DOMAIN-SUFFIX,b23.tv,DIRECT
  - DOMAIN-SUFFIX,bilicdn1.com,DIRECT
  - DOMAIN-SUFFIX,biliapi.net,DIRECT
  - DOMAIN-SUFFIX,biliapi.com,DIRECT
  - DOMAIN-SUFFIX,hdslb.com,DIRECT
  - DOMAIN-SUFFIX,akamaized.net,DIRECT
  - DOMAIN-KEYWORD,bilibili,DIRECT

  # WeChat / Tencent IM — forced DIRECT (user requested).
  - DOMAIN-SUFFIX,wechat.com,DIRECT
  - DOMAIN-SUFFIX,weixin.qq.com,DIRECT
  - DOMAIN-SUFFIX,weixin.com,DIRECT
  - DOMAIN-SUFFIX,qpic.cn,DIRECT
  - DOMAIN-SUFFIX,wx.qlogo.cn,DIRECT
  - DOMAIN-SUFFIX,qq.com,DIRECT
  - DOMAIN-SUFFIX,qlogo.cn,DIRECT
  - DOMAIN-SUFFIX,gtimg.com,DIRECT
  - DOMAIN-SUFFIX,gtimg.cn,DIRECT
  - DOMAIN-SUFFIX,tencent.com,DIRECT
  - DOMAIN-SUFFIX,tencent-cloud.net,DIRECT
  - DOMAIN-KEYWORD,wechat,DIRECT
  - DOMAIN-KEYWORD,weixin,DIRECT

  # Xiaohongshu — forced DIRECT (user requested).
  - DOMAIN-SUFFIX,xiaohongshu.com,DIRECT
  - DOMAIN-SUFFIX,xhscdn.com,DIRECT
  - DOMAIN-SUFFIX,xhsstatic.com,DIRECT
  - DOMAIN-SUFFIX,rednotecdn.com,DIRECT
  - DOMAIN-SUFFIX,xhs.cn,DIRECT
  - DOMAIN-KEYWORD,xiaohongshu,DIRECT
  - DOMAIN-KEYWORD,xhscdn,DIRECT

  # Everything else — through Proxy by default.
  - MATCH,Proxy
"#,
        host = host,
        vless_port = vless_port,
        hy2_port = hy2_port,
        sni = sni,
        uuid = uuid,
        hy2_pass = hy2_pass,
        pub_key = pub_key,
        short_id = short_id,
    )
}

/// Ultra-minimal Clash/Mihomo config for ClashMi rules-mode bug (issue #195).
///
/// Strips everything optional: no rule-providers, no GEOIP, IPv4-only, single
/// proxy node (CDN-VMess only), one proxy-group. All routing decisions are
/// made by inline DOMAIN-SUFFIX rules to minimize work for the rules engine.
/// Mainland China major domains go DIRECT inline; everything else goes
/// through CDN-VMess.
pub fn build_clash_yaml_ios_minimal(uuid: &str, cdn_host: Option<&str>) -> String {
    let h = cdn_host.unwrap_or("cdn.example.com");
    format!(
        r#"# Generated by godo-vps (iOS minimal variant) — for ClashMi issue #195 workaround.
# No rule-providers, no GEOIP, IPv4-only, single proxy. Refresh subscription to update.
mixed-port: 7890
mode: rule
log-level: silent
ipv6: false

dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "{h}"
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  fallback:
    - 1.1.1.1
    - 8.8.8.8

sniffer:
  enable: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    TLS:
      ports: [443]
    QUIC:
      ports: [443]

proxies:
  - name: CDN
    type: vmess
    server: {h}
    port: 443
    uuid: {uuid}
    alterId: 0
    cipher: auto
    network: ws
    tls: true
    servername: {h}
    skip-cert-verify: false
    ws-opts:
      path: /vmws
      headers:
        Host: {h}

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - CDN
      - DIRECT

rules:
  - DOMAIN-SUFFIX,{h},DIRECT
  - DOMAIN-SUFFIX,xn--7xa.monster,DIRECT
  - DOMAIN-SUFFIX,anthropic.com,Proxy
  - DOMAIN-SUFFIX,claude.ai,Proxy
  - DOMAIN-KEYWORD,claude,Proxy
  - DOMAIN-SUFFIX,openai.com,Proxy
  - DOMAIN-SUFFIX,chatgpt.com,Proxy
  - DOMAIN-SUFFIX,oaistatic.com,Proxy
  - DOMAIN-SUFFIX,oaiusercontent.com,Proxy
  - DOMAIN-KEYWORD,openai,Proxy
  - DOMAIN-SUFFIX,bing.com,Proxy
  - DOMAIN-SUFFIX,b-msn.com,Proxy
  - DOMAIN-SUFFIX,google.com,Proxy
  - DOMAIN-SUFFIX,googleapis.com,Proxy
  - DOMAIN-SUFFIX,gstatic.com,Proxy
  - DOMAIN-SUFFIX,youtube.com,Proxy
  - DOMAIN-SUFFIX,ytimg.com,Proxy
  - DOMAIN-SUFFIX,ggpht.com,Proxy
  - DOMAIN-SUFFIX,facebook.com,Proxy
  - DOMAIN-SUFFIX,fbcdn.net,Proxy
  - DOMAIN-SUFFIX,instagram.com,Proxy
  - DOMAIN-SUFFIX,twitter.com,Proxy
  - DOMAIN-SUFFIX,x.com,Proxy
  - DOMAIN-SUFFIX,t.co,Proxy
  - DOMAIN-SUFFIX,github.com,Proxy
  - DOMAIN-SUFFIX,githubusercontent.com,Proxy
  - DOMAIN-SUFFIX,githubassets.com,Proxy
  - DOMAIN-SUFFIX,wikipedia.org,Proxy
  - DOMAIN-SUFFIX,reddit.com,Proxy
  - DOMAIN-SUFFIX,discord.com,Proxy
  - DOMAIN-SUFFIX,telegram.org,Proxy
  - DOMAIN-SUFFIX,t.me,Proxy
  - DOMAIN-SUFFIX,whatsapp.com,Proxy
  - DOMAIN-SUFFIX,netflix.com,Proxy
  - DOMAIN-SUFFIX,nflxvideo.net,Proxy
  - DOMAIN-SUFFIX,spotify.com,Proxy
  - DOMAIN-SUFFIX,cn,DIRECT
  - DOMAIN-SUFFIX,baidu.com,DIRECT
  - DOMAIN-SUFFIX,bdimg.com,DIRECT
  - DOMAIN-SUFFIX,bdstatic.com,DIRECT
  - DOMAIN-SUFFIX,bilibili.com,DIRECT
  - DOMAIN-SUFFIX,bilivideo.com,DIRECT
  - DOMAIN-SUFFIX,b23.tv,DIRECT
  - DOMAIN-SUFFIX,hdslb.com,DIRECT
  - DOMAIN-SUFFIX,weibo.com,DIRECT
  - DOMAIN-SUFFIX,weibo.cn,DIRECT
  - DOMAIN-SUFFIX,sinaimg.cn,DIRECT
  - DOMAIN-SUFFIX,weixin.qq.com,DIRECT
  - DOMAIN-SUFFIX,wechat.com,DIRECT
  - DOMAIN-SUFFIX,qq.com,DIRECT
  - DOMAIN-SUFFIX,tencent.com,DIRECT
  - DOMAIN-SUFFIX,qpic.cn,DIRECT
  - DOMAIN-SUFFIX,gtimg.cn,DIRECT
  - DOMAIN-SUFFIX,douyin.com,DIRECT
  - DOMAIN-SUFFIX,douyinpic.com,DIRECT
  - DOMAIN-SUFFIX,douyinvod.com,DIRECT
  - DOMAIN-SUFFIX,bytedance.com,DIRECT
  - DOMAIN-SUFFIX,toutiao.com,DIRECT
  - DOMAIN-SUFFIX,xiaohongshu.com,DIRECT
  - DOMAIN-SUFFIX,xhscdn.com,DIRECT
  - DOMAIN-SUFFIX,zhihu.com,DIRECT
  - DOMAIN-SUFFIX,zhimg.com,DIRECT
  - DOMAIN-SUFFIX,iqiyi.com,DIRECT
  - DOMAIN-SUFFIX,youku.com,DIRECT
  - DOMAIN-SUFFIX,mgtv.com,DIRECT
  - DOMAIN-SUFFIX,alipay.com,DIRECT
  - DOMAIN-SUFFIX,alipayobjects.com,DIRECT
  - DOMAIN-SUFFIX,taobao.com,DIRECT
  - DOMAIN-SUFFIX,tmall.com,DIRECT
  - DOMAIN-SUFFIX,tbcdn.cn,DIRECT
  - DOMAIN-SUFFIX,jd.com,DIRECT
  - DOMAIN-SUFFIX,360buyimg.com,DIRECT
  - DOMAIN-SUFFIX,meituan.com,DIRECT
  - DOMAIN-SUFFIX,meituan.net,DIRECT
  - DOMAIN-SUFFIX,dianping.com,DIRECT
  - DOMAIN-SUFFIX,aliyun.com,DIRECT
  - DOMAIN-SUFFIX,aliyuncs.com,DIRECT
  - DOMAIN-SUFFIX,163.com,DIRECT
  - DOMAIN-SUFFIX,126.com,DIRECT
  - DOMAIN-SUFFIX,netease.com,DIRECT
  - DOMAIN-SUFFIX,sina.com.cn,DIRECT
  - DOMAIN-SUFFIX,sohu.com,DIRECT
  - DOMAIN-SUFFIX,12306.cn,DIRECT
  - DOMAIN-SUFFIX,gov.cn,DIRECT
  - DOMAIN-SUFFIX,edu.cn,DIRECT
  - MATCH,Proxy
"#,
        h = h,
        uuid = uuid,
    )
}
