use crate::cli::ClientConfigArgs;
use anyhow::Result;
use colored::Colorize;
use std::fs;

pub async fn run(args: ClientConfigArgs) -> Result<()> {
    let yaml = if args.ios {
        build_clash_yaml_ios(
            &args.host, args.vless_port, args.hy2_port,
            &args.sni, &args.uuid,
            &args.hy2_password, &args.reality_public_key, &args.reality_short_id,
            args.cdn_host.as_deref(),
        )
    } else {
        build_clash_yaml(
            &args.host, args.vless_port, args.hy2_port,
            &args.sni, &args.uuid,
            &args.hy2_password, &args.reality_public_key, &args.reality_short_id,
            args.cdn_host.as_deref(),
        )
    };

    match args.output {
        Some(ref path) => {
            fs::write(path, &yaml)?;
            println!("{}", format!("✓ Clash config written to {path}").green());
        }
        None => print!("{yaml}"),
    }

    Ok(())
}

pub fn build_clash_yaml(
    host: &str, vless_port: u16, hy2_port: u16,
    sni: &str, uuid: &str,
    hy2_pass: &str, pub_key: &str, short_id: &str,
    cdn_host: Option<&str>,
) -> String {
    let cdn_proxy = match cdn_host {
        Some(h) => format!(
            "\n  - name: \"CDN-VMess\"\n    \
             type: vmess\n    \
             server: {h}\n    \
             port: 443\n    \
             uuid: {uuid}\n    \
             alterId: 0\n    \
             cipher: auto\n    \
             network: ws\n    \
             tls: true\n    \
             servername: {h}\n    \
             skip-cert-verify: false\n    \
             ws-opts:\n      \
               path: /vmws\n      \
               headers:\n        \
                 Host: {h}\n"
        ),
        None => String::new(),
    };
    let cdn_in_fallback = if cdn_host.is_some() {
        "      - CDN-VMess\n"
    } else {
        ""
    };
    let cdn_in_select = if cdn_host.is_some() {
        "      - CDN-VMess\n"
    } else {
        ""
    };
    format!(
        r#"# Generated by godo-vps — edit rule-providers URLs if jsdelivr is blocked
mixed-port: 7890
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090
external-ui: ui

dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - localhost.ptlogin2.qq.com
  listen: 0.0.0.0:53
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - https://1.1.1.1/dns-query
    - https://dns.google/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4

proxies:
  - name: "SG-Reality"
    type: vless
    server: {host}
    port: {vless_port}
    uuid: {uuid}
    flow: xtls-rprx-vision
    network: tcp
    tls: true
    servername: {sni}
    reality-opts:
      public-key: {pub_key}
      short-id: {short_id}
    client-fingerprint: chrome

  - name: "SG-Hysteria2"
    type: hysteria2
    server: {host}
    port: {hy2_port}
    password: {hy2_pass}
    sni: www.bing.com
    skip-cert-verify: true
    up: "30 Mbps"
    down: "200 Mbps"
{cdn_proxy}
proxy-groups:
  - name: "🚀 Proxy"
    type: fallback
    proxies:
{cdn_in_fallback}      - SG-Hysteria2
      - SG-Reality
    url: "https://www.gstatic.com/generate_204"
    interval: 60
    lazy: true

  - name: "🔀 Select"
    type: select
    proxies:
      - 🚀 Proxy
{cdn_in_select}      - SG-Reality
      - SG-Hysteria2
      - DIRECT

  - name: "🤖 OpenAI"
    type: select
    proxies:
      - SG-Reality
      - SG-Hysteria2

  - name: "📺 Streaming"
    type: select
    proxies:
      - SG-Reality
      - SG-Hysteria2
      - DIRECT

  - name: "🐟 Final"
    type: select
    proxies:
      - 🚀 Proxy
      - DIRECT

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400
  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400
  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400
  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400
  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400
  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

rules:
  - RULE-SET,reject,REJECT

  # === HKUST campus → 直连（最高优先级，不让校内流量绕到新加坡） ===
  - IP-CIDR,143.89.0.0/16,DIRECT,no-resolve
  - IP-CIDR,175.159.0.0/16,DIRECT,no-resolve

  # === 香港本地 → 直连 ===
  - GEOIP,HK,DIRECT,no-resolve
  - DOMAIN-SUFFIX,hk,DIRECT
  - DOMAIN-SUFFIX,com.hk,DIRECT
  - DOMAIN-SUFFIX,edu.hk,DIRECT
  - DOMAIN-SUFFIX,gov.hk,DIRECT
  - DOMAIN-SUFFIX,org.hk,DIRECT
  - DOMAIN-SUFFIX,net.hk,DIRECT

  # === Steam / Valve 游戏（Deadlock/CS2/Dota2 等）→ 直连，避免代理拖延迟 ===
  # NOTE: DST-PORT range syntax (e.g. 27015-27050) is rejected by the OG Clash
  # core that Clash for Windows ships with. Stick to domain rules; Steam clients
  # resolve hostnames first so this catches the vast majority of game traffic.
  - DOMAIN-SUFFIX,steamserver.net,DIRECT
  - DOMAIN-SUFFIX,steamcontent.com,DIRECT
  - DOMAIN-SUFFIX,steamstatic.com,DIRECT
  - DOMAIN-KEYWORD,steampipe,DIRECT
  - DOMAIN-KEYWORD,steamcdn,DIRECT

  # === 国内社交/视频/IM 强制直连（即使被误判也不走代理） ===
  - DOMAIN-SUFFIX,xiaohongshu.com,DIRECT
  - DOMAIN-SUFFIX,xhscdn.com,DIRECT
  - DOMAIN-SUFFIX,rednotecdn.com,DIRECT
  - DOMAIN-SUFFIX,rnote.com,DIRECT
  - DOMAIN-SUFFIX,xhsstatic.com,DIRECT
  - DOMAIN-SUFFIX,bilibili.com,DIRECT
  - DOMAIN-SUFFIX,bilivideo.com,DIRECT
  - DOMAIN-SUFFIX,b23.tv,DIRECT
  - DOMAIN-KEYWORD,upos-,DIRECT
  - DOMAIN-SUFFIX,hdslb.com,DIRECT
  - DOMAIN-SUFFIX,weibo.com,DIRECT
  - DOMAIN-SUFFIX,weibo.cn,DIRECT
  - DOMAIN-SUFFIX,sinaimg.cn,DIRECT
  - DOMAIN-SUFFIX,sina.com.cn,DIRECT
  - DOMAIN-SUFFIX,wx.qq.com,DIRECT
  - DOMAIN-SUFFIX,weixin.qq.com,DIRECT
  - DOMAIN-SUFFIX,wechat.com,DIRECT
  - DOMAIN-SUFFIX,qq.com,DIRECT
  - DOMAIN-SUFFIX,tencent.com,DIRECT
  - DOMAIN-SUFFIX,tencent-cloud.net,DIRECT    # 微信视频号 P2P CDN
  - DOMAIN-SUFFIX,qpic.cn,DIRECT
  - DOMAIN-SUFFIX,gtimg.com,DIRECT
  - DOMAIN-SUFFIX,gtimg.cn,DIRECT
  - DOMAIN-SUFFIX,douyin.com,DIRECT
  - DOMAIN-SUFFIX,douyinpic.com,DIRECT
  - DOMAIN-SUFFIX,douyinvod.com,DIRECT
  - DOMAIN-SUFFIX,toutiao.com,DIRECT
  - DOMAIN-SUFFIX,zhihu.com,DIRECT
  - DOMAIN-SUFFIX,zhimg.com,DIRECT
  - DOMAIN-SUFFIX,ixigua.com,DIRECT
  - DOMAIN-SUFFIX,iqiyi.com,DIRECT
  - DOMAIN-SUFFIX,iqiyipic.com,DIRECT
  - DOMAIN-SUFFIX,youku.com,DIRECT
  - DOMAIN-SUFFIX,ykimg.com,DIRECT
  - DOMAIN-SUFFIX,mgtv.com,DIRECT
  - DOMAIN-SUFFIX,hitv.com,DIRECT
  - DOMAIN-SUFFIX,alipay.com,DIRECT
  - DOMAIN-SUFFIX,alipayobjects.com,DIRECT
  - DOMAIN-SUFFIX,taobao.com,DIRECT
  - DOMAIN-SUFFIX,tmall.com,DIRECT
  - DOMAIN-SUFFIX,jd.com,DIRECT
  - DOMAIN-SUFFIX,360buyimg.com,DIRECT
  - DOMAIN-SUFFIX,meituan.com,DIRECT
  - DOMAIN-SUFFIX,meituan.net,DIRECT

  # === 原有规则 ===
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,🚀 Proxy
  - DOMAIN-KEYWORD,openai,🤖 OpenAI
  - DOMAIN-KEYWORD,claude,🤖 OpenAI
  - DOMAIN-SUFFIX,netflix.com,📺 Streaming
  - DOMAIN-SUFFIX,nflxvideo.net,📺 Streaming
  - DOMAIN-SUFFIX,spotify.com,📺 Streaming
  - RULE-SET,telegramcidr,🚀 Proxy,no-resolve
  - RULE-SET,proxy,🚀 Proxy
  - RULE-SET,gfw,🚀 Proxy
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT,no-resolve
  - RULE-SET,cncidr,DIRECT,no-resolve
  - GEOIP,LAN,DIRECT,no-resolve
  - GEOIP,CN,DIRECT,no-resolve
  - MATCH,🐟 Final
"#,
        host = host,
        vless_port = vless_port,
        hy2_port = hy2_port,
        sni = sni,
        uuid = uuid,
        hy2_pass = hy2_pass,
        pub_key = pub_key,
        short_id = short_id,
    )
}

/// iOS-friendly Clash/Mihomo config:
///  - no dns.listen (iOS VPN extension sandbox forbids socket binds)
///  - redir-host instead of fake-ip (more reliable inside the extension)
///  - no external-controller / external-ui / allow-lan / bind-address (sandbox)
///  - rule-providers trimmed to 3 essentials (gfw + cncidr + proxy) to stay
///    under iOS's 50 MB VPN-extension memory cap.
pub fn build_clash_yaml_ios(
    host: &str, vless_port: u16, hy2_port: u16,
    sni: &str, uuid: &str,
    hy2_pass: &str, pub_key: &str, short_id: &str,
    cdn_host: Option<&str>,
) -> String {
    let cdn_proxy = match cdn_host {
        Some(h) => format!(
            "\n  - name: \"CDN-VMess\"\n    \
             type: vmess\n    \
             server: {h}\n    \
             port: 443\n    \
             uuid: {uuid}\n    \
             alterId: 0\n    \
             cipher: auto\n    \
             network: ws\n    \
             tls: true\n    \
             servername: {h}\n    \
             skip-cert-verify: false\n    \
             ws-opts:\n      \
               path: /vmws\n      \
               headers:\n        \
                 Host: {h}\n"
        ),
        None => String::new(),
    };
    let cdn_in_fallback = if cdn_host.is_some() { "      - CDN-VMess\n" } else { "" };
    let cdn_in_select   = if cdn_host.is_some() { "      - CDN-VMess\n" } else { "" };

    format!(
        r#"# Generated by godo-vps (iOS variant) — trimmed for ClashMi / mihomo on iOS
# iOS VPN extension has a hard 50 MB memory limit; do not add more rule-providers
mixed-port: 7890
mode: rule
log-level: silent
ipv6: true

dns:
  enable: true
  ipv6: true
  enhanced-mode: redir-host
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - https://1.1.1.1/dns-query
    - https://dns.google/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN

proxies:
  - name: "SG-Reality"
    type: vless
    server: {host}
    port: {vless_port}
    uuid: {uuid}
    flow: xtls-rprx-vision
    network: tcp
    tls: true
    servername: {sni}
    reality-opts:
      public-key: {pub_key}
      short-id: {short_id}
    client-fingerprint: chrome

  - name: "SG-Hysteria2"
    type: hysteria2
    server: {host}
    port: {hy2_port}
    password: {hy2_pass}
    sni: www.bing.com
    skip-cert-verify: true
    up: "30 Mbps"
    down: "200 Mbps"
{cdn_proxy}
proxy-groups:
  - name: "🚀 Proxy"
    type: fallback
    proxies:
{cdn_in_fallback}      - SG-Hysteria2
      - SG-Reality
    url: "https://www.gstatic.com/generate_204"
    interval: 60
    lazy: true

  - name: "🔀 Select"
    type: select
    proxies:
      - 🚀 Proxy
{cdn_in_select}      - SG-Reality
      - SG-Hysteria2
      - DIRECT

rule-providers:
  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400
  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

rules:
  # === 我们自己的代理域名永远直连，否则会死循环 ===
  - DOMAIN-SUFFIX,xn--7xa.monster,DIRECT

  # === HKUST 校园 → 直连 ===
  - IP-CIDR,143.89.0.0/16,DIRECT,no-resolve
  - IP-CIDR,175.159.0.0/16,DIRECT,no-resolve

  # === 国内大厂域名（最常用的，inline 进来，省 rule-provider）===
  - DOMAIN-SUFFIX,xiaohongshu.com,DIRECT
  - DOMAIN-SUFFIX,xhscdn.com,DIRECT
  - DOMAIN-SUFFIX,bilibili.com,DIRECT
  - DOMAIN-SUFFIX,bilivideo.com,DIRECT
  - DOMAIN-SUFFIX,b23.tv,DIRECT
  - DOMAIN-SUFFIX,hdslb.com,DIRECT
  - DOMAIN-SUFFIX,weibo.com,DIRECT
  - DOMAIN-SUFFIX,weixin.qq.com,DIRECT
  - DOMAIN-SUFFIX,wechat.com,DIRECT
  - DOMAIN-SUFFIX,qq.com,DIRECT
  - DOMAIN-SUFFIX,tencent.com,DIRECT
  - DOMAIN-SUFFIX,qpic.cn,DIRECT
  - DOMAIN-SUFFIX,gtimg.cn,DIRECT
  - DOMAIN-SUFFIX,douyin.com,DIRECT
  - DOMAIN-SUFFIX,douyinpic.com,DIRECT
  - DOMAIN-SUFFIX,douyinvod.com,DIRECT
  - DOMAIN-SUFFIX,zhihu.com,DIRECT
  - DOMAIN-SUFFIX,zhimg.com,DIRECT
  - DOMAIN-SUFFIX,iqiyi.com,DIRECT
  - DOMAIN-SUFFIX,youku.com,DIRECT
  - DOMAIN-SUFFIX,mgtv.com,DIRECT
  - DOMAIN-SUFFIX,alipay.com,DIRECT
  - DOMAIN-SUFFIX,taobao.com,DIRECT
  - DOMAIN-SUFFIX,tmall.com,DIRECT
  - DOMAIN-SUFFIX,jd.com,DIRECT
  - DOMAIN-SUFFIX,meituan.com,DIRECT
  - DOMAIN-SUFFIX,meituan.net,DIRECT

  # === 香港本地 → 直连 ===
  - GEOIP,HK,DIRECT,no-resolve
  - DOMAIN-SUFFIX,hk,DIRECT

  # === 走代理的关键服务 ===
  - DOMAIN-KEYWORD,openai,🚀 Proxy
  - DOMAIN-KEYWORD,claude,🚀 Proxy
  - DOMAIN-SUFFIX,anthropic.com,🚀 Proxy
  - DOMAIN-SUFFIX,netflix.com,🚀 Proxy
  - DOMAIN-SUFFIX,spotify.com,🚀 Proxy

  # === 规则集（仅保留 3 个核心，控制内存）===
  - RULE-SET,gfw,🚀 Proxy
  - RULE-SET,proxy,🚀 Proxy
  - RULE-SET,cncidr,DIRECT,no-resolve

  # === 最终兜底 ===
  - GEOIP,LAN,DIRECT,no-resolve
  - GEOIP,CN,DIRECT,no-resolve
  - MATCH,🚀 Proxy
"#,
        host = host,
        vless_port = vless_port,
        hy2_port = hy2_port,
        sni = sni,
        uuid = uuid,
        hy2_pass = hy2_pass,
        pub_key = pub_key,
        short_id = short_id,
    )
}
